[workspace]
members = ["projects/*"]
default-members = [
#    "projects/sub_projects",
#    "projects/dist-web",
    "projects/dist-server",
]
exclude = [
    "projects/.DS_Store",
]

[profile.release]
lto = true
panic = "abort"
